#!/usr/bin/env bash
# =============================================================================
# update-whitelist.sh — Regenerate Squid domain whitelist from .env
# =============================================================================
# Usage:
#   ./scripts/update-whitelist.sh             (reads ../.env)
#   ./scripts/update-whitelist.sh /path/.env  (reads custom .env)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${1:-$PROJECT_DIR/.env}"
ACL_FILE="$PROJECT_DIR/squid/whitelist.acl"

# ── Load .env ─────────────────────────────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  echo "❌  .env file not found at: $ENV_FILE"
  echo "    Copy .env.example → .env and fill in your values first."
  exit 1
fi

# Source only relevant variables (safe — no code execution)
COMPANY_DOMAIN=""
COPILOT_DOMAIN=""
EXTRA_ALLOWED_DOMAINS=""

while IFS='=' read -r key value; do
  # Strip comments and blank lines
  [[ "$key" =~ ^[[:space:]]*# ]] && continue
  [[ -z "$key" ]] && continue
  # Strip inline comments and surrounding quotes
  value="$(echo "$value" | sed 's/#.*//' | xargs)"
  case "$key" in
    COMPANY_DOMAIN)         COMPANY_DOMAIN="$value" ;;
    COPILOT_DOMAIN)         COPILOT_DOMAIN="$value" ;;
    EXTRA_ALLOWED_DOMAINS)  EXTRA_ALLOWED_DOMAINS="$value" ;;
  esac
done < "$ENV_FILE"

# ── Validate required values ──────────────────────────────────────────────────
if [[ -z "$COMPANY_DOMAIN" ]]; then
  echo "❌  COMPANY_DOMAIN is not set in $ENV_FILE"
  exit 1
fi
if [[ -z "$COPILOT_DOMAIN" ]]; then
  echo "⚠️   COPILOT_DOMAIN is not set — only COMPANY_DOMAIN will be whitelisted"
fi

# ── Build whitelist ───────────────────────────────────────────────────────────
cat > "$ACL_FILE" << HEADER
# =============================================================================
# Squid Domain Whitelist — /etc/squid/whitelist.acl
# =============================================================================
# AUTO-GENERATED by scripts/update-whitelist.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Source: $ENV_FILE
#
# Format:
#   .domain.com  → matches domain.com AND all subdomains
#   domain.com   → matches only the exact domain
# =============================================================================

HEADER

# Company domain (always wildcarded → matches all subdomains)
echo "# ── Company Domain ───────────────────────────────────────────────────────────" >> "$ACL_FILE"
echo ".${COMPANY_DOMAIN}" >> "$ACL_FILE"
echo "" >> "$ACL_FILE"

# Copilot/AI domain
if [[ -n "$COPILOT_DOMAIN" ]]; then
  echo "# ── AI Copilot / LLM API ─────────────────────────────────────────────────────" >> "$ACL_FILE"
  # If it starts with a dot, use as-is; otherwise prepend dot for subdomain matching
  # Strip leading dot if present, then always write with dot prefix.
  # In Squid, .domain.com matches BOTH domain.com and *.domain.com — no need for both.
  COPILOT_DOMAIN="${COPILOT_DOMAIN#.}"
  echo ".${COPILOT_DOMAIN}" >> "$ACL_FILE"
  echo "" >> "$ACL_FILE"
fi

# Extra domains
if [[ -n "$EXTRA_ALLOWED_DOMAINS" ]]; then
  echo "# ── Extra Allowed Domains ────────────────────────────────────────────────────" >> "$ACL_FILE"
  IFS=',' read -ra EXTRAS <<< "$EXTRA_ALLOWED_DOMAINS"
  for domain in "${EXTRAS[@]}"; do
    domain="$(echo "$domain" | xargs)"  # trim spaces
    [[ -z "$domain" ]] && continue
    # Strip leading dot if present, always write with dot prefix
    domain="${domain#.}"
    echo ".${domain}" >> "$ACL_FILE"
  done
  echo "" >> "$ACL_FILE"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo "✅  Whitelist written to: $ACL_FILE"
echo ""
echo "   Allowed domains:"
echo "     Company:  .${COMPANY_DOMAIN}  (and all subdomains)"
[[ -n "$COPILOT_DOMAIN" ]] && echo "     Copilot:  ${COPILOT_DOMAIN}  (and all subdomains)"
if [[ -n "$EXTRA_ALLOWED_DOMAINS" ]]; then
  echo "     Extras:   $EXTRA_ALLOWED_DOMAINS"
fi

echo ""
echo "   Restart proxy to apply:"
echo "     docker compose restart squid-proxy"